# Test Run: metrics.tests.test_permanent_computations.test_serializers

Total tests: 54
Passed: 0
Failed: 0
Errors: 54

## test_action_remark_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.002 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,205 - metrics - DEBUG - Starting test: test_action_remark_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_anomaly_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,208 - metrics - DEBUG - Starting test: test_anomaly_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_bulk_create_metrics (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,210 - metrics - DEBUG - Starting test: test_bulk_create_metrics (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_category_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,212 - metrics - DEBUG - Starting test: test_category_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_computation_status_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,215 - metrics - DEBUG - Starting test: test_computation_status_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_connection_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,217 - metrics - DEBUG - Starting test: test_connection_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_correlation_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,219 - metrics - DEBUG - Starting test: test_correlation_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_custom_method_to_representation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,221 - metrics - DEBUG - Starting test: test_custom_method_to_representation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_custom_user_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,223 - metrics - DEBUG - Starting test: test_custom_user_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_dashboard_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.002 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,226 - metrics - DEBUG - Starting test: test_dashboard_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_data_quality_score_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,229 - metrics - DEBUG - Starting test: test_data_quality_score_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_date_time_field_handling (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,231 - metrics - DEBUG - Starting test: test_date_time_field_handling (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_domain_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,233 - metrics - DEBUG - Starting test: test_domain_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,235 - metrics - DEBUG - Starting test: test_experiment_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,237 - metrics - DEBUG - Starting test: test_experiment_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_metric_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,239 - metrics - DEBUG - Starting test: test_experiment_metric_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_nested_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,242 - metrics - DEBUG - Starting test: test_experiment_nested_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_read_only_fields (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,244 - metrics - DEBUG - Starting test: test_experiment_read_only_fields (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,245 - metrics - DEBUG - Starting test: test_experiment_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_experiment_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,247 - metrics - DEBUG - Starting test: test_experiment_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_forecast_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,249 - metrics - DEBUG - Starting test: test_forecast_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_historical_data_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,251 - metrics - DEBUG - Starting test: test_historical_data_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_impact_analysis_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,253 - metrics - DEBUG - Starting test: test_impact_analysis_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_insight_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,256 - metrics - DEBUG - Starting test: test_insight_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_many_to_many_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,258 - metrics - DEBUG - Starting test: test_many_to_many_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,260 - metrics - DEBUG - Starting test: test_metric_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,262 - metrics - DEBUG - Starting test: test_metric_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_error_handling (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,264 - metrics - DEBUG - Starting test: test_metric_error_handling (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_metadata_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,267 - metrics - DEBUG - Starting test: test_metric_metadata_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,269 - metrics - DEBUG - Starting test: test_metric_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_target_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,270 - metrics - DEBUG - Starting test: test_metric_target_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_metric_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,272 - metrics - DEBUG - Starting test: test_metric_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_moving_average_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,274 - metrics - DEBUG - Starting test: test_moving_average_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_network_analysis_result_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,276 - metrics - DEBUG - Starting test: test_network_analysis_result_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_notification_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,278 - metrics - DEBUG - Starting test: test_notification_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_pending_computation_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,280 - metrics - DEBUG - Starting test: test_pending_computation_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_project_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,283 - metrics - DEBUG - Starting test: test_project_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_complex_field_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,285 - metrics - DEBUG - Starting test: test_report_complex_field_deserialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_complex_field_serialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,287 - metrics - DEBUG - Starting test: test_report_complex_field_serialization (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_complex_field_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,289 - metrics - DEBUG - Starting test: test_report_complex_field_validation (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,291 - metrics - DEBUG - Starting test: test_report_edge_cases (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_metric_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,294 - metrics - DEBUG - Starting test: test_report_metric_relationship (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_report_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,296 - metrics - DEBUG - Starting test: test_report_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_seasonality_result_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,298 - metrics - DEBUG - Starting test: test_seasonality_result_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_strategy_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,300 - metrics - DEBUG - Starting test: test_strategy_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_tactical_solution_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,302 - metrics - DEBUG - Starting test: test_tactical_solution_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_tag_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,304 - metrics - DEBUG - Starting test: test_tag_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_team_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,306 - metrics - DEBUG - Starting test: test_team_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_technical_indicator_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,308 - metrics - DEBUG - Starting test: test_technical_indicator_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_time_dimension_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,310 - metrics - DEBUG - Starting test: test_time_dimension_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_trend_change_point_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,312 - metrics - DEBUG - Starting test: test_trend_change_point_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_trend_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,314 - metrics - DEBUG - Starting test: test_trend_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_user_profile_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,316 - metrics - DEBUG - Starting test: test_user_profile_serializer (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

## test_write_only_field (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
Status: error
Duration: 0.001 seconds

### Error
```
Traceback (most recent call last):
  File "/home/nadeemramli/workspace/github.com/nadeemramli/mapping-of-metrics/metric-map-app/backend/metricMapAPI/metrics/tests/test_permanent_computations/test_serializers.py", line 33, in setUp
    self.client = Client.objects.create(
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/nadeemramli/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django_tenants/models.py", line 100, in save
    raise Exception("Can't create tenant outside the public schema. "
Exception: Can't create tenant outside the public schema. Current schema is test.
```

### Output
```
2024-08-07 18:07:05,318 - metrics - DEBUG - Starting test: test_write_only_field (metrics.tests.test_permanent_computations.test_serializers.SerializerTestCase)
```

